install: true
language: cpp
addons:
  apt:
   sources:
    - ubuntu-toolchain-r-test
   packages:
    - g++-4.9
  apt_packages:
    - gfortran
sudo: required
python: 
- '3.6'
before_install:
- git clone --depth=50 --branch=master https://github.com/OpenMatrixLanguage/Continuous_Integration_Linux.git Linux
env:
  MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
  SH=bash
  OML_ROOT=$PWD
  OML_THIRDPARTY=$PWD/Linux/third_party
  LD_LIBRARY_PATH=$OML_THIRDPARTY/fftw/fftw-3.2.2/.libs:$LD_LIBRARY_PATH
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OML_THIRDPARTY/lapack/lapack-3.7.1
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OML_THIRDPARTY/ANTLR/libantlr3c-3.4/.libs
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OML_THIRDPARTY/matio/matio-1.5.11/src/.libs
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OML_THIRDPARTY/hdf5/hdf5-1.10.1/hdf5/lib
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OML_THIRDPARTY/sundials/sundials-3.1.0-install/lib
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OML_ROOT/src/bin/linux64
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/bin:/usr/lib
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/x86_64-linux-gnu
  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lib/x86_64-linux-gnu
  PATH=$PATH:$OML_ROOT/src/bin/linux64
  OML_PYTHONHOME=/usr
  OML_PYTHONVERSION=python3
  OML_PYTHON_NUMPYDIR=$OML_PYTHONHOME/lib/$OML_PYTHONVERSION/dist-packages/numpy/core/include/numpy/
before_script:
script:
- g++ --version
- cd $OML_ROOT/src
- ls -alF
- make -f makefile.open
after_success:
#- chmod 777 $OML_ROOT/src/bin/linux64/omlconsole
- ls -alF $OML_ROOT/src/bin/linux64
- cd $OML_ROOT/Tests/RegressionTests && pwd
- perl ../regressOMLConsole.pl -travis
- cd $OML_ROOT/Tests && pwd
- source run_toolbox_tests.sh
- cd $OML_ROOT/Tests
- source evaluate_test_results.sh
#compiler: gcc
