git rm delete2.oml
git rm eig22.oml
git rm fileparts6.oml
git rm fileparts7.oml
git rm filetest10.oml
git rm filetest121.oml
git rm filetest124.oml
git rm filetest143.oml
git rm filetest145.oml
git rm filetest15.oml
git rm filetest22.oml
git rm filetest27.oml
git rm filetest29.oml
git rm filetest40.oml
git rm filetest54.oml
git rm filetest66.oml
git rm filetest68.oml
git rm filetest69.oml
git rm filetest6.oml
git rm filetest70.oml
git rm filetest78.oml
git rm filetest7.oml
git rm filetest88.oml
git rm filetest8.oml
git rm filetest92.oml
git rm filetest97.oml
git rm filetest9.oml
git rm fscanf18.oml
git rm fullfile1.oml
git rm fullfile2.oml
git rm isspace2.oml
git rm movefile01.oml
git rm movefile02.oml
git rm movefile03.oml
git rm movefile04.oml
git rm movefile05.oml
git rm movefile06.oml
git rm movefile07.oml
git rm movefile08.oml
git rm movefile09.oml
git rm movefile10.oml
git rm movefile11.oml
git rm movefile12.oml
git rm movefile13.oml
git rm movefile14.oml
git rm movefile15.oml
git rm movefile16.oml
git rm movefile17.oml
git rm movefile18.oml
git rm movefile19.oml
git rm movefile99.oml
git rm norm62.oml
git rm regexp26.oml
git rm regexp27.oml
git rm round10.oml
git rm sp_matrix_divide14.oml
git rm sp_matrix_divide16.oml
git rm sp_matrix_divide18.oml
git rm sp_matrix_divide3.oml
git rm sprintf28.oml
git rm sprintf29.oml
git rm sprintf30.oml
git rm sprintf32.oml
git rm system1.oml
git rm system2.oml
git rm textscan22.oml
git rm textscan24.oml

git rm RefLogs/delete2.log
git rm RefLogs/eig22.log
git rm RefLogs/fileparts6.log
git rm RefLogs/fileparts7.log
git rm RefLogs/filetest10.log
git rm RefLogs/filetest121.log
git rm RefLogs/filetest124.log
git rm RefLogs/filetest143.log
git rm RefLogs/filetest145.log
git rm RefLogs/filetest15.log
git rm RefLogs/filetest22.log
git rm RefLogs/filetest27.log
git rm RefLogs/filetest29.log
git rm RefLogs/filetest40.log
git rm RefLogs/filetest54.log
git rm RefLogs/filetest66.log
git rm RefLogs/filetest68.log
git rm RefLogs/filetest69.log
git rm RefLogs/filetest6.log
git rm RefLogs/filetest70.log
git rm RefLogs/filetest78.log
git rm RefLogs/filetest7.log
git rm RefLogs/filetest88.log
git rm RefLogs/filetest8.log
git rm RefLogs/filetest92.log
git rm RefLogs/filetest97.log
git rm RefLogs/filetest9.log
git rm RefLogs/fscanf18.log
git rm RefLogs/fullfile1.log
git rm RefLogs/fullfile2.log
git rm RefLogs/isspace2.log
git rm RefLogs/movefile01.log
git rm RefLogs/movefile02.log
git rm RefLogs/movefile03.log
git rm RefLogs/movefile04.log
git rm RefLogs/movefile05.log
git rm RefLogs/movefile06.log
git rm RefLogs/movefile07.log
git rm RefLogs/movefile08.log
git rm RefLogs/movefile09.log
git rm RefLogs/movefile10.log
git rm RefLogs/movefile11.log
git rm RefLogs/movefile12.log
git rm RefLogs/movefile13.log
git rm RefLogs/movefile14.log
git rm RefLogs/movefile15.log
git rm RefLogs/movefile16.log
git rm RefLogs/movefile17.log
git rm RefLogs/movefile18.log
git rm RefLogs/movefile19.log
git rm RefLogs/movefile99.log
git rm RefLogs/norm62.log
git rm RefLogs/regexp26.log
git rm RefLogs/regexp27.log
git rm RefLogs/round10.log
git rm RefLogs/sp_matrix_divide14.log
git rm RefLogs/sp_matrix_divide16.log
git rm RefLogs/sp_matrix_divide18.log
git rm RefLogs/sp_matrix_divide3.log
git rm RefLogs/sprintf28.log
git rm RefLogs/sprintf29.log
git rm RefLogs/sprintf30.log
git rm RefLogs/sprintf32.log
git rm RefLogs/system1.log
git rm RefLogs/system2.log
git rm RefLogs/textscan22.log
git rm RefLogs/textscan24.log