git rm delete2.oml
git rm fileparts6.oml
git rm fileparts7.oml
git rm fileread1.oml
git rm filetest121.oml
git rm filetest124.oml
git rm filetest143.oml
git rm filetest15.oml
git rm filetest54.oml
git rm filetest66.oml
git rm filetest68.oml
git rm filetest69.oml
git rm filetest70.oml
git rm filetest88.oml
git rm filetest97.oml
git rm fscanf18.oml
git rm fullfile1.oml
git rm fullfile2.oml
git rm isspace2.oml
git rm regexp26.oml
git rm regexp27.oml
git rm setfield62.oml
git rm sp_matrix_divide14.oml
git rm sp_matrix_divide16.oml
git rm sp_matrix_divide3.oml
git rm sprintf28.oml
git rm sprintf29.oml
git rm sprintf30.oml
git rm sprintf32.oml
git rm system1.oml
git rm system2.oml
