# ====================================================================
# OpenMatrix oml/toolboxes/omljson makefile
# ====================================================================
PROJ := omljson

UNAME := $(shell uname)
ifneq (,$(findstring NT,$(UNAME)))
   TARGET = $(BINDIR)/$(PROJ).dll
else
   TARGET = $(BINDIR)/lib$(PROJ).so
endif

include $(OML_ROOT)/src/makebase.cfg

# ====================================================================
SOURCES += $(wildcard *.cxx)
OBJECTS = $(foreach file,$(SOURCES),$(addprefix $(PLATFORM)/,$(addsuffix .o,$(basename $(notdir $(file))))))
vpath %.cxx _private

CXX_DEFINES += -DMATIOOMLTBOX_EXPORT 

CXX_INCLUDES += -I. $(HWMATHKERNEL_INC)
CXX_INCLUDES += -I$(OML_ROOT)/src/oml/Runtime

LIBS += $(MATHKERNEL_LIBS)
LIBS += $(OML_LIBS)

# ====================================================================

$(PLATFORM)/%.o : %.cxx $(objdir)
	$(compile-cxx)

$(TARGET) : $(OBJECTS)
	$(build-shared-lib)

clean::
	-$(RM) -rf $(TARGET)
	-$(RM) -rf $(PLATFORM)
	-$(RM) -rf $(BINDIR)/$(PROJ).*
	-$(RM) -rf $(LIBDIR)/$(PROJ).*

